# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('school', models.CharField(max_length=50)),
                ('year', models.DateField()),
                ('text', models.CharField(max_length=300)),
                ('impact', models.CharField(max_length=300)),
                ('github', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
